services:
  - type: web
    name: TransCare
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        value: sqlite:///instance/database.db
    disk:
      name: db-disk
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
